spring:
  application:
    name: messagingservice
  cloud:
      config:
        uri: http://localhost:8090
management:
        security:
          enabled: false
name: Messaging Service version 1.0
server:
  port: 21906